author: Maximelc
author_url: https://maximelc.github.io/
github_url: https://github.com/Maximelc/WeekdayPicker
root_url: https://maximelc.github.io/WeekdayPicker/
module: WeekdayPicker
output: docs
theme: fullwidth
