# rule identifiers to exclude from running
disabled_rules:
  - todo
  - large_tuple
  - trailing_whitespace
  - redundant_string_enum_value

# some rules are only opt-in
opt_in_rules:
  - empty_count
  - force_unwrapping

line_length:
  warning: 200
  error: 250

excluded:
  - Tests

file_length: 600
type_body_length: 300
function_body_length: 80