update_fastlane

default_platform :ios

platform :ios do
    
    before_all do |lane, options|

    end

    desc "Release a new pod version"        
    lane :pod do
    	# put code to automatically submit new pod version
        error do |lane, exception|
        end
    end    
end